# -*- coding: utf-8 -*-
"""FitnessPrniciplesScrapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uj8-6XEDNXbOnjAqyGjNEjQGLdzafJUb
"""
import requests
from bs4 import BeautifulSoup
import markdownify

# 1. Define the target URL
url = "https://psu.pb.unizin.org/kines61psusl/chapter/fitness-principles/"
print(f"🌐 Fetching URL: {url}")

# 2. Send the request
headers = {
    "User-Agent": "Mozilla/5.0"
}
response = requests.get(url, headers=headers)
response.raise_for_status()
print("✅ Fetch complete.")

# 3. Parse with BeautifulSoup
soup = BeautifulSoup(response.content, "html.parser")

# 4. Extract the main content body
# Try to find the main chapter content div
content_div = soup.find("div", class_="chapter")
if not content_div:
    print("⚠️ Could not find 'chapter' class. Falling back to body.")
    content_div = soup.find("body")

# 5. Convert HTML content to Markdown
markdown_text = markdownify.markdownify(str(content_div), heading_style="ATX")

# 6. Save to .md file
filename = "fitness_principles.md"
with open(filename, "w", encoding="utf-8") as f:
    f.write(markdown_text)

print(f"📄 Saved to {filename} ({len(markdown_text)} characters).")